#!/bin/bash

#SBATCH --job-name=hp1a25
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --partition=sched_mit_binz
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --constraint=centos7

module load engaging/openmpi/2.0.3


export dir=/home/aplatham2/Programs/gromacs-2018.4/bin
export tabledir=/pool001/aplatham2/HP12/DNA_tables
export salt=159

echo 0 0 | $dir/gmx_mpi trjconv -f eq.gro -s eq.tpr -pbc mol -ur compact -o eq2.gro -center
#echo 0 | $dir/gmx_mpi trjconv -f eq.xtc -s eq.tpr -pbc mol -ur compact -o eq2.gro -b 99000 -e 99000
$dir/gmx_mpi editconf -f eq2.gro -o eq2.gro -box 25.0 25.0 25.0

$dir/gmx_mpi grompp -f min.mdp -c eq2.gro -p chromatin_dna.top -o eq_min.tpr
$dir/gmx_mpi mdrun -deffnm eq_min -table table_$salt.xvg -tablep table_smog$salt.xvg

$dir/gmx_mpi grompp -f eq3.mdp -c eq_min.gro -p chromatin_dna.top -o eq3.tpr  -maxwarn 1
mpirun -np 16 $dir/gmx_mpi mdrun -deffnm eq3 -dlb yes -table table_$salt.xvg -tablep table_smog$salt.xvg -maxh 23.9 -noddcheck -rdd 4
