martinize2 -f molecules/mole_0.pdb -nt -o molecules_MARTINI/PROA_0.top -ff martini3001 -x molecules_MARTINI/mole_0.pdb -maxwarn 100
martinize2 -f molecules/mole_1.pdb -nt -o molecules_MARTINI/PROA_1.top -ff martini3001 -x molecules_MARTINI/mole_1.pdb -maxwarn 100
martinize2 -f molecules/mole_2.pdb -nt -o molecules_MARTINI/PROA_2.top -ff martini3001 -x molecules_MARTINI/mole_2.pdb -maxwarn 100
martinize2 -f molecules/mole_3.pdb -nt -o molecules_MARTINI/PROA_3.top -ff martini3001 -x molecules_MARTINI/mole_3.pdb -maxwarn 100
martinize2 -f molecules/mole_4.pdb -nt -o molecules_MARTINI/PROA_4.top -ff martini3001 -x molecules_MARTINI/mole_4.pdb -maxwarn 100
martinize2 -f molecules/mole_5.pdb -nt -o molecules_MARTINI/PROA_5.top -ff martini3001 -x molecules_MARTINI/mole_5.pdb -maxwarn 100
martinize2 -f molecules/mole_6.pdb -nt -o molecules_MARTINI/PROA_6.top -ff martini3001 -x molecules_MARTINI/mole_6.pdb -maxwarn 100
martinize2 -f molecules/mole_7.pdb -nt -o molecules_MARTINI/PROA_7.top -ff martini3001 -x molecules_MARTINI/mole_7.pdb -maxwarn 100
martinize2 -f molecules/mole_8.pdb -nt -o molecules_MARTINI/PROA_8.top -ff martini3001 -x molecules_MARTINI/mole_8.pdb -maxwarn 100
martinize2 -f molecules/mole_9.pdb -nt -o molecules_MARTINI/PROA_9.top -ff martini3001 -x molecules_MARTINI/mole_9.pdb -maxwarn 100
martinize2 -f molecules/mole_10.pdb -nt -o molecules_MARTINI/PROA_10.top -ff martini3001 -x molecules_MARTINI/mole_10.pdb -maxwarn 100
martinize2 -f molecules/mole_11.pdb -nt -o molecules_MARTINI/PROA_11.top -ff martini3001 -x molecules_MARTINI/mole_11.pdb -maxwarn 100
martinize2 -f molecules/mole_12.pdb -nt -o molecules_MARTINI/PROA_12.top -ff martini3001 -x molecules_MARTINI/mole_12.pdb -maxwarn 100
martinize2 -f molecules/mole_13.pdb -nt -o molecules_MARTINI/PROA_13.top -ff martini3001 -x molecules_MARTINI/mole_13.pdb -maxwarn 100
martinize2 -f molecules/mole_14.pdb -nt -o molecules_MARTINI/PROA_14.top -ff martini3001 -x molecules_MARTINI/mole_14.pdb -maxwarn 100
martinize2 -f molecules/mole_15.pdb -nt -o molecules_MARTINI/PROA_15.top -ff martini3001 -x molecules_MARTINI/mole_15.pdb -maxwarn 100
martinize2 -f molecules/mole_16.pdb -nt -o molecules_MARTINI/PROA_16.top -ff martini3001 -x molecules_MARTINI/mole_16.pdb -maxwarn 100
martinize2 -f molecules/mole_17.pdb -nt -o molecules_MARTINI/PROA_17.top -ff martini3001 -x molecules_MARTINI/mole_17.pdb -maxwarn 100
martinize2 -f molecules/mole_18.pdb -nt -o molecules_MARTINI/PROA_18.top -ff martini3001 -x molecules_MARTINI/mole_18.pdb -maxwarn 100
martinize2 -f molecules/mole_19.pdb -nt -o molecules_MARTINI/PROA_19.top -ff martini3001 -x molecules_MARTINI/mole_19.pdb -maxwarn 100
