#!/bin/bash

#SBATCH --job-name=1NPM125
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --partition=sched_mit_binz
#SBATCH --time=4:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --constraint=centos7

module load engaging/openmpi/2.0.3


export dir=/home/aplatham2/Programs/gromacs-2018.4/bin
export tabledir=/pool001/aplatham2/HP12/DNA_tables
export salt=159

$dir/gmx_mpi grompp -f prod_0.mdp -c eq3.gro -p chromatin_dna.top -t eq3.cpt -o prod_0.tpr  -maxwarn 1
mpirun -np 16 $dir/gmx_mpi mdrun -deffnm prod_0 -dlb yes -table table_$salt.xvg -tablep table_smog$salt.xvg -maxh 0.25   -noddcheck  -rdd 4
