#!/bin/bash

#SBATCH --job-name=1med125
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --array=2-10%1
#SBATCH --partition=sched_mit_binz
#SBATCH --exclude=node[762-942]
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --constraint=centos7

module load engaging/openmpi/2.0.3
export tabledir=/pool001/aplatham2/HP12/DNA_tables
export salt=159

mpirun -np 16 /home/aplatham2/Programs/gromacs-2018.4/bin/gmx_mpi mdrun -deffnm prod_0 -cpi -append -table table_$salt.xvg -tablep table_smog$salt.xvg -maxh 47.9 -dlb yes  -noddcheck -rdd 4
