martinize2 -f molecules/mole_0.pdb -nt -o molecules_MARTINI/PROA_0.top -ff martini3001 -x molecules_MARTINI/mole_0.pdb
martinize2 -f molecules/mole_1.pdb -nt -o molecules_MARTINI/PROA_1.top -ff martini3001 -x molecules_MARTINI/mole_1.pdb
martinize2 -f molecules/mole_2.pdb -nt -o molecules_MARTINI/PROA_2.top -ff martini3001 -x molecules_MARTINI/mole_2.pdb
martinize2 -f molecules/mole_3.pdb -nt -o molecules_MARTINI/PROA_3.top -ff martini3001 -x molecules_MARTINI/mole_3.pdb
martinize2 -f molecules/mole_4.pdb -nt -o molecules_MARTINI/PROA_4.top -ff martini3001 -x molecules_MARTINI/mole_4.pdb
martinize2 -f molecules/mole_5.pdb -nt -o molecules_MARTINI/PROA_5.top -ff martini3001 -x molecules_MARTINI/mole_5.pdb
martinize2 -f molecules/mole_6.pdb -nt -o molecules_MARTINI/PROA_6.top -ff martini3001 -x molecules_MARTINI/mole_6.pdb
martinize2 -f molecules/mole_7.pdb -nt -o molecules_MARTINI/PROA_7.top -ff martini3001 -x molecules_MARTINI/mole_7.pdb
martinize2 -f molecules/mole_8.pdb -nt -o molecules_MARTINI/PROA_8.top -ff martini3001 -x molecules_MARTINI/mole_8.pdb
martinize2 -f molecules/mole_9.pdb -nt -o molecules_MARTINI/PROA_9.top -ff martini3001 -x molecules_MARTINI/mole_9.pdb
martinize2 -f molecules/mole_10.pdb -nt -o molecules_MARTINI/PROA_10.top -ff martini3001 -x molecules_MARTINI/mole_10.pdb
martinize2 -f molecules/mole_11.pdb -nt -o molecules_MARTINI/PROA_11.top -ff martini3001 -x molecules_MARTINI/mole_11.pdb
martinize2 -f molecules/mole_12.pdb -nt -o molecules_MARTINI/PROA_12.top -ff martini3001 -x molecules_MARTINI/mole_12.pdb
martinize2 -f molecules/mole_13.pdb -nt -o molecules_MARTINI/PROA_13.top -ff martini3001 -x molecules_MARTINI/mole_13.pdb
martinize2 -f molecules/mole_14.pdb -nt -o molecules_MARTINI/PROA_14.top -ff martini3001 -x molecules_MARTINI/mole_14.pdb
martinize2 -f molecules/mole_15.pdb -nt -o molecules_MARTINI/PROA_15.top -ff martini3001 -x molecules_MARTINI/mole_15.pdb
martinize2 -f molecules/mole_16.pdb -nt -o molecules_MARTINI/PROA_16.top -ff martini3001 -x molecules_MARTINI/mole_16.pdb
martinize2 -f molecules/mole_17.pdb -nt -o molecules_MARTINI/PROA_17.top -ff martini3001 -x molecules_MARTINI/mole_17.pdb
martinize2 -f molecules/mole_18.pdb -nt -o molecules_MARTINI/PROA_18.top -ff martini3001 -x molecules_MARTINI/mole_18.pdb
martinize2 -f molecules/mole_19.pdb -nt -o molecules_MARTINI/PROA_19.top -ff martini3001 -x molecules_MARTINI/mole_19.pdb
martinize2 -f molecules/mole_20.pdb -nt -o molecules_MARTINI/PROA_20.top -ff martini3001 -x molecules_MARTINI/mole_20.pdb
martinize2 -f molecules/mole_21.pdb -nt -o molecules_MARTINI/PROA_21.top -ff martini3001 -x molecules_MARTINI/mole_21.pdb
martinize2 -f molecules/mole_22.pdb -nt -o molecules_MARTINI/PROA_22.top -ff martini3001 -x molecules_MARTINI/mole_22.pdb
martinize2 -f molecules/mole_23.pdb -nt -o molecules_MARTINI/PROA_23.top -ff martini3001 -x molecules_MARTINI/mole_23.pdb
martinize2 -f molecules/mole_24.pdb -nt -o molecules_MARTINI/PROA_24.top -ff martini3001 -x molecules_MARTINI/mole_24.pdb
martinize2 -f molecules/mole_25.pdb -nt -o molecules_MARTINI/PROA_25.top -ff martini3001 -x molecules_MARTINI/mole_25.pdb
martinize2 -f molecules/mole_26.pdb -nt -o molecules_MARTINI/PROA_26.top -ff martini3001 -x molecules_MARTINI/mole_26.pdb
martinize2 -f molecules/mole_27.pdb -nt -o molecules_MARTINI/PROA_27.top -ff martini3001 -x molecules_MARTINI/mole_27.pdb
martinize2 -f molecules/mole_28.pdb -nt -o molecules_MARTINI/PROA_28.top -ff martini3001 -x molecules_MARTINI/mole_28.pdb
martinize2 -f molecules/mole_29.pdb -nt -o molecules_MARTINI/PROA_29.top -ff martini3001 -x molecules_MARTINI/mole_29.pdb
martinize2 -f molecules/mole_30.pdb -nt -o molecules_MARTINI/PROA_30.top -ff martini3001 -x molecules_MARTINI/mole_30.pdb
martinize2 -f molecules/mole_31.pdb -nt -o molecules_MARTINI/PROA_31.top -ff martini3001 -x molecules_MARTINI/mole_31.pdb
martinize2 -f molecules/mole_32.pdb -nt -o molecules_MARTINI/PROA_32.top -ff martini3001 -x molecules_MARTINI/mole_32.pdb
martinize2 -f molecules/mole_33.pdb -nt -o molecules_MARTINI/PROA_33.top -ff martini3001 -x molecules_MARTINI/mole_33.pdb
martinize2 -f molecules/mole_34.pdb -nt -o molecules_MARTINI/PROA_34.top -ff martini3001 -x molecules_MARTINI/mole_34.pdb
martinize2 -f molecules/mole_35.pdb -nt -o molecules_MARTINI/PROA_35.top -ff martini3001 -x molecules_MARTINI/mole_35.pdb
martinize2 -f molecules/mole_36.pdb -nt -o molecules_MARTINI/PROA_36.top -ff martini3001 -x molecules_MARTINI/mole_36.pdb
martinize2 -f molecules/mole_37.pdb -nt -o molecules_MARTINI/PROA_37.top -ff martini3001 -x molecules_MARTINI/mole_37.pdb
martinize2 -f molecules/mole_38.pdb -nt -o molecules_MARTINI/PROA_38.top -ff martini3001 -x molecules_MARTINI/mole_38.pdb
martinize2 -f molecules/mole_39.pdb -nt -o molecules_MARTINI/PROA_39.top -ff martini3001 -x molecules_MARTINI/mole_39.pdb
martinize2 -f molecules/mole_40.pdb -nt -o molecules_MARTINI/PROA_40.top -ff martini3001 -x molecules_MARTINI/mole_40.pdb
martinize2 -f molecules/mole_41.pdb -nt -o molecules_MARTINI/PROA_41.top -ff martini3001 -x molecules_MARTINI/mole_41.pdb
martinize2 -f molecules/mole_42.pdb -nt -o molecules_MARTINI/PROA_42.top -ff martini3001 -x molecules_MARTINI/mole_42.pdb
martinize2 -f molecules/mole_43.pdb -nt -o molecules_MARTINI/PROA_43.top -ff martini3001 -x molecules_MARTINI/mole_43.pdb
martinize2 -f molecules/mole_44.pdb -nt -o molecules_MARTINI/PROA_44.top -ff martini3001 -x molecules_MARTINI/mole_44.pdb
martinize2 -f molecules/mole_45.pdb -nt -o molecules_MARTINI/PROA_45.top -ff martini3001 -x molecules_MARTINI/mole_45.pdb
martinize2 -f molecules/mole_46.pdb -nt -o molecules_MARTINI/PROA_46.top -ff martini3001 -x molecules_MARTINI/mole_46.pdb
